# Galacticus Docker image
# code downloads: https://users.obs.carnegiescience.edu/abenson/galacticus/versions/
FROM centos:6

RUN yum -y update &&\
    yum -y install vim wget patch gcc-gfortran git
    
# install source code
RUN cd /usr/local &&\
    wget http://users.obs.carnegiescience.edu/abenson/galacticus/versions/galacticus.tar.bz2 &&\
    tar xvfj galacticus.tar.bz2
    
# install data
RUN cd /usr/local &&\
    wget http://users.obs.carnegiescience.edu/abenson/galacticus/versions/galacticus_datasets.tar.bz2 &&\
    tar xvfj galacticus_datasets.tar.bz2
    
# download pre-compiled binary
RUN cd /usr/local/galacticus &&\
    #wget https://users.obs.carnegiescience.edu/abenson/galacticus/versions/galacticus_default_latest_x86_64.exe &&\
    wget -O Galacticus.exe https://bitbucket.org/galacticusdev/galacticus/downloads/galacticus_workflow.exe &&\
    chmod u=wrx Galacticus.exe
    
# set environment
ENV GALACTICUS_EXEC_PATH /usr/local/galacticus
ENV GALACTICUS_DATA_PATH /usr/local/galacticus_datasets
ENV PATH .:$PATH

# copy parameters template
#COPY parameters/quickTest.xml /usr/local/galacticus/parameters/quickTest.xml
COPY parameters/ /usr/local/galacticus/parameters/

# script to execute the model with input arguments
COPY scripts/run_galacticus.sh /usr/local/galacticus/run_galacticus.sh

# working directory
WORKDIR /usr/local/galacticus

#ENTRYPOINT /usr/local/galacticus/run_galacticus.sh
