# Galacticus Docker image
# code downloads: https://users.obs.carnegiescience.edu/abenson/galacticus/versions/
FROM centos:7

RUN yum -y update &&\
    yum -y install vim wget patch gcc-gfortran git bzip2 make &&\
    yum -y install libgfortran5

# install HDF5 libraries to inspect output
RUN yum install –y epel-release &&\
    yum-config-manager -y --enable epel &&\
    yum install -y hdf5-devel
    
# install source code
RUN cd /usr/local &&\
    wget http://users.obs.carnegiescience.edu/abenson/galacticus/versions/galacticus.tar.bz2 &&\
    tar xvfj galacticus.tar.bz2
    
# install data
RUN cd /usr/local &&\
    wget http://users.obs.carnegiescience.edu/abenson/galacticus/versions/galacticus_datasets.tar.bz2 &&\
    tar xvfj galacticus_datasets.tar.bz2
    
# download pre-compiled binary
RUN cd /usr/local/galacticus &&\
    #wget https://users.obs.carnegiescience.edu/abenson/galacticus/versions/galacticus_default_latest_x86_64.exe &&\
    wget -O Galacticus.exe https://bitbucket.org/galacticusdev/galacticus/downloads/galacticus_workflow.exe &&\
    chmod u=wrx Galacticus.exe
    
# set environment
ENV GALACTICUS_EXEC_PATH=/usr/local/galacticus
ENV GALACTICUS_DATA_PATH=/usr/local/galacticus_datasets
ENV PATH=.:$PATH
ENV LD_LIBRARY_PATH=/usr/local/lib64:/usr/lib64:/usr/local/lib:/usr/lib/gcc/x86_64-redhat-linux/4.4.4/

# download additional executables into GALACTICUS_DATA_PATH
RUN cd $GALACTICUS_DATA_PATH &&\
    wget https://bitbucket.org/galacticusdev/galacticus/downloads/tools.tar.bz2 &&\
    tar xvfj tools.tar.bz2

# copy parameters template
#COPY parameters/quickTest.xml /usr/local/galacticus/parameters/quickTest.xml
COPY parameters/ /usr/local/galacticus/parameters/

# script to execute the model with input arguments
COPY scripts/run_galacticus.sh /usr/local/galacticus/run_galacticus.sh

# working directory
WORKDIR /usr/local/galacticus

# cleanup
RUN rm /usr/local/galacticus_datasets/tools.tar.bz2 \
       /usr/local/galacticus_datasets.tar.bz2 \
       /usr/local/galacticus.tar.bz2

#ENTRYPOINT /usr/local/galacticus/run_galacticus.sh
