# Kubernetes job to run a single iteration of Galacticus
apiVersion: batch/v1
kind: Job
metadata:
  generateName: galacticus-
  labels:
    app: galacticus
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: galacticus
          image: galacticus/galacticus
          command:
            - /usr/local/galacticus/run_galacticus.sh
          envFrom:
            - configMapRef:
                name: galacticus-config
          volumeMounts:
            - name: data-directory
              mountPath: /data         
      volumes: 
        - name: data-directory
          hostPath:
            path: /tmp
            type: Directory
